package aliases

import (
	"fmt"
	"strings"

	"github.com/Prettyletto/Allyas/internal/domain/models"
	"github.com/Prettyletto/Allyas/internal/infra/storage"
	"github.com/google/uuid"
)

type CreateInput struct {
	StorePath   string
	SourcePath  string
	Name        string
	Command     string
	Group       string
	Description string
	Tags        []string
}

type CreateOutput struct {
	ID   string
	Name string
}

func createAlias(in CreateInput) (CreateOutput, error) {
	store, err := storage.LoadStore(in.StorePath)
	if err != nil {
		return CreateOutput{}, fmt.Errorf("load stroe: %w", err)
	}

	normName := strings.ToLower(strings.TrimSpace(in.Name))
	for _, a := range store.Aliases {
		if strings.ToLower(strings.TrimSpace(a.Name)) == normName {
			return CreateOutput{}, fmt.Errorf("alias %q already exists", in.Name)
		}
	}

	id := uuid.NewString()
	alias, err := models.NewAlias(id, in.Name, in.Command, models.AliasParams{
		Group:       in.Group,
		Description: in.Description,
		Tags:        in.Tags,
	})
	if err != nil {
		return CreateOutput{}, err
	}

	store.Aliases = append(store.Aliases, *alias)
	if err := storage.SaveStore(in.StorePath, store); err != nil {
		return CreateOutput{}, fmt.Errorf("save store: %w", err)
	}
	source := renderSource(store)
	if err := storage.SaveSource(in.SourcePath, source); err != nil {
		return CreateOutput{}, fmt.Errorf("save source: %w", err)
	}

	return CreateOutput{ID: alias.ID, Name: alias.Name}, nil
}
func renderSource(store models.Store) string {
	var b strings.Builder
	b.WriteString("# generated by allyas\n")
	for _, a := range store.Aliases {
		fmt.Fprintf(&b, "alias %s='%s'\n", a.Name, a.Command)
	}
	return b.String()
}

func Run(in CreateInput) (CreateOutput, error) {
	return createAlias(in)
}
