package shell

import "fmt"

func RenderHook(sourcePath, binaryName string) string {
	return fmt.Sprintf(`# generated by allyas 
if [ -f %q ]; then
	. %q
fi

allyas__run_tracked() {
	allyas_id="$1"
	shift
	allyas_cmd="$1"
	shift

	ALLYAS_SHELL_WRAPPER=1 command %s __record "$allyas_id" >/dev/null 2>&1 || true
	eval "$allyas_cmd"
}

ax() {
	ALLYAS_SHELL_WRAPPER=1 command %s "$@"
	allyas_status=$?

	if [ $allyas_status -eq 0 ]; then
		case "$1" in
			create|edit|remove|init|import)
				if [ -f %q ]; then
					. %q
				fi
				;;
		esac
	fi
	
return $allyas_status
}
`, sourcePath, sourcePath, binaryName, binaryName, sourcePath, sourcePath)
}
