package shell

import "fmt"

func RenderHook(sourcePath, binaryName string) string {
	return fmt.Sprintf(`# generated by allyas 
if [ -f %q ]; then
	. %q
fi

ax() {
	ALLYAS_SHELL_WRAPPER=1 command %s "$@"
	allyas_status=$?

	if [ $allyas_status -eq 0 ]; then
		case "$1" in
			create|edit|remove|init)
				if [ -f %q ]; then
					. %q
				fi
				;;
		esac
	fi
	
return $allyas_status
}
`, sourcePath, sourcePath, binaryName, sourcePath, sourcePath)
}
