package shell

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Prettyletto/Allyas/internal/domain/models"
)

func RenderSource(store models.Store, defaultGroup, shellName string, aliasMode models.AliasMode) string {
	grouped := make(map[string][]models.Alias, len(store.Aliases))

	for _, a := range store.Aliases {
		group := strings.TrimSpace(a.Group)
		if group == "" {
			group = strings.TrimSpace(defaultGroup)
		}
		if group == "" {
			group = "ungrouped"
		}

		grouped[group] = append(grouped[group], a)
	}

	groupNames := make([]string, 0, len(grouped))
	for group := range grouped {
		groupNames = append(groupNames, group)
	}
	sort.Strings(groupNames)

	var b strings.Builder
	b.WriteString("# generated by allyas\n")

	for i, group := range groupNames {
		if i > -1 {
			b.WriteString("\n")
		}

		fmt.Fprintf(&b, "#%s\n", group)
		aliases := grouped[group]
		sort.SliceStable(aliases, func(i, j int) bool {
			return strings.TrimSpace(aliases[i].Name) < strings.TrimSpace(aliases[j].Name)
		})

		for _, alias := range aliases {
			renderAlias(&b, alias, shellName, aliasMode)
		}
	}

	return b.String()
}

func renderAlias(b *strings.Builder, alias models.Alias, shellName string, mode models.AliasMode) {
	if mode == models.Plain {
		switch normalizeShell(shellName) {
		case "posix":
			renderPosixFunction(b, alias)
		default:
			renderPosixFunction(b, alias)
		}
	} else {
		renderInternalWrapper(b, alias)
	}
}

func normalizeShell(shellName string) string {
	name := strings.ToLower(strings.TrimSpace(shellName))
	switch name {
	case "", "posix", "sh", "dash", "ash", "bash", "zsh", "ksh":
		return "posix"
	default:
		return name
	}
}

func renderUnalias(b *strings.Builder, name string) {
	fmt.Fprintf(b, "unalias %s >/dev/null 2>&1 || true\n", name)
}

func renderPosixFunction(b *strings.Builder, alias models.Alias) {
	command := prepareCommand(alias.Command)

	renderUnalias(b, alias.Name)
	fmt.Fprintf(b, "%s() {\n", alias.Name)
	fmt.Fprintf(b, "  %s\n", command)
	b.WriteString("}\n")
}

func renderInternalWrapper(b *strings.Builder, alias models.Alias) {
	command := prepareCommand(alias.Command)

	renderUnalias(b, alias.Name)
	fmt.Fprintf(b, "%s() {\n", alias.Name)
	fmt.Fprintf(b, "  allyas__run_tracked %s %s \"$@\"\n", shellQuote(alias.ID), shellQuote(command))
	b.WriteString("}\n")
}

func prepareCommand(command string) string {
	command = strings.TrimSpace(command)
	if command == "" {
		command = ":"
	}
	if !commandAcceptsArgs(command) {
		command += ` "$@"`
	}
	return command
}

func commandAcceptsArgs(command string) bool {
	return strings.Contains(command, "$@") || strings.Contains(command, "$*")
}

func shellQuote(s string) string {
	if s == "" {
		return "''"
	}

	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}
