package shell

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Prettyletto/Allyas/internal/domain/models"
)

func RenderSource(store models.Store, defaultGroup, shellName string) string {
	grouped := make(map[string][]models.Alias, len(store.Aliases))

	for _, a := range store.Aliases {
		group := strings.TrimSpace(a.Group)
		if group == "" {
			group = strings.TrimSpace(defaultGroup)
		}
		if group == "" {
			group = "ungrouped"
		}

		grouped[group] = append(grouped[group], a)
	}

	groupNames := make([]string, 0, len(grouped))
	for group := range grouped {
		groupNames = append(groupNames, group)
	}
	sort.Strings(groupNames)

	var b strings.Builder
	b.WriteString("# generated by allyas\n")

	for i, group := range groupNames {
		if i > -1 {
			b.WriteString("\n")
		}

		fmt.Fprintf(&b, "#%s\n", group)
		aliases := grouped[group]
		sort.SliceStable(aliases, func(i, j int) bool {
			return strings.TrimSpace(aliases[i].Name) < strings.TrimSpace(aliases[j].Name)
		})

		for _, alias := range aliases {
			renderAlias(&b, alias, shellName)
		}
	}

	return b.String()
}

func renderAlias(b *strings.Builder, alias models.Alias, shellName string) {
	switch normalizeShell(shellName) {
	case "posix":
		renderPosixFunction(b, alias)
	default:
		renderPosixFunction(b, alias)
	}
}

func normalizeShell(shellName string) string {
	name := strings.ToLower(strings.TrimSpace(shellName))
	switch name {
	case "", "posix", "sh", "dash", "ash", "bash", "zsh", "ksh":
		return "posix"
	default:
		return name
	}
}

func renderPosixFunction(b *strings.Builder, alias models.Alias) {
	command := strings.TrimSpace(alias.Command)
	if command == "" {
		command = ":"
	}
	if !commandAcceptsArgs(command) {
		command += ` "$@"`
	}

	fmt.Fprintf(b, "%s() {\n", alias.Name)
	fmt.Fprintf(b, "  %s\n", command)
	b.WriteString("}\n")
}

func commandAcceptsArgs(command string) bool {
	return strings.Contains(command, "$@") || strings.Contains(command, "$*")
}
