package storage

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/Prettyletto/Allyas/internal/domain/models"
)

func LoadSource(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	if len(data) == 0 {
		return "", fmt.Errorf("source file is empty, try to use the command <allyas init>")
	}

	return string(data), nil
}

func SaveSource(path, content string) error {
	if _, err := EnsureAppConfigDir(); err != nil {
		return fmt.Errorf("resolve configure dir path: %w", err)
	}

	if err := os.WriteFile(path, []byte(content), WritePerm); err != nil {
		return fmt.Errorf("error writing a source file: %w", err)
	}

	return nil
}

func RenderSource(store models.Store, defaultGroup string) string {
	grouped := make(map[string][]models.Alias, len(store.Aliases))

	for _, a := range store.Aliases {
		g := strings.TrimSpace(a.Group)
		if g == "" {
			g = strings.TrimSpace(defaultGroup)
		}
		if g == "" {
			g = "ungrouped"
		}
		grouped[g] = append(grouped[g], a)
	}
	groupNames := make([]string, 0, len(grouped))
	for g := range grouped {
		groupNames = append(groupNames, g)
	}
	sort.Strings(groupNames)

	var b strings.Builder
	b.WriteString("# generated by allyas\n")

	for i, g := range groupNames {
		if i > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "#%s\n", g)
		aliases := grouped[g]
		sort.SliceStable(aliases, func(i, j int) bool {
			return strings.TrimSpace(aliases[i].Name) <
				strings.TrimSpace(aliases[j].Name)
		})

		for _, a := range aliases {
			fmt.Fprintf(&b, "alias %s=%s\n", a.Name, shellSingleQuote(a.Command))

		}
	}
	return b.String()
}

func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}
